# Generated by Django 2.2.4 on 2020-04-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('update_timestamp', models.BigIntegerField(default=0, verbose_name='Когда изменено')),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=100, verbose_name='Провайдер')),
                ('uid', models.CharField(max_length=255, verbose_name='Ид пользователя у провайдера')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Фамилия у провайдера')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='Имя у провайдера')),
                ('display_name', models.CharField(default='', max_length=255, verbose_name='Отображаемое имя у провайдера')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='Email у провайдера')),
                ('photo', models.URLField(default='', max_length=255, verbose_name='Фото у провайдера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'uid')},
            },
        ),
    ]
