# Generated by Django 2.2.4 on 2020-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncognitoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('private_key', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='Личный ключ')),
                ('public_key', models.CharField(db_index=True, max_length=36, null=True, unique=True, verbose_name='Публичный ключ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
