# Generated by Django 2.2.4 on 2020-06-05 11:09

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Заполнить IncognitoUser.update_timestamp
    """
    IncognitoUser = apps.get_model('users', 'IncognitoUser')
    print('')
    print("Fill IncognitoUser.update_timestamp from insert_timestamp")
    for incognitouser in IncognitoUser.objects.all().iterator(chunk_size=100):
        insert_timestamp = incognitouser.insert_timestamp
        if insert_timestamp:
            IncognitoUser.objects.filter(pk=incognitouser.pk).update(update_timestamp=insert_timestamp)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_incognitouser_update_timestamp'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
