# Generated by Django 2.2.4 on 2020-06-29 11:02

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_data_fill_incognitouser_update_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=app.models.files_upload_to, verbose_name='Фото')),
                ('photo_original_filename', models.CharField(default='', editable=False, max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'middle_name'),
            },
            bases=(app.models.FilesMixin, models.Model),
        ),
    ]
