# Generated by Django 2.2.4 on 2020-06-29 11:03

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Заполнить Profile.uuids, просто добавив profiles к существующим users
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('users', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
