# Generated by Django 2.2.4 on 2020-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200629_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fame',
            field=models.PositiveIntegerField(default=0, verbose_name='Известность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sum_thanks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число благодарностей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trustless_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число утрат доверия'),
        ),
    ]
