# Generated by Django 2.2.4 on 2020-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_data_fill_profile_url_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incognitouser',
            name='update_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено'),
        ),
        migrations.AlterField(
            model_name='oauth',
            name='update_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено'),
        ),
    ]
