# Generated by Django 2.2.4 on 2020-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201023_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='trustless_count',
            new_name='mistrust_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число оказанных доверий'),
        ),
    ]
