# Generated by Django 2.2.4 on 2020-11-10 15:16

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    print('')
    print ('Recount Profile trust_count, mistrust_count, fame')
    n_all = n = 0
    Profile = apps.get_model('users', 'Profile')
    CurrentState = apps.get_model('contact', 'CurrentState')
    for profile in Profile.objects.all().select_related('user'):
        n_all += 1
        user = profile.user
        trust_count = CurrentState.objects.filter(
            is_reverse=False,
            user_to=user,
            is_trust=True,
        ).distinct().count()
        mistrust_count = CurrentState.objects.filter(
            is_reverse=False,
            user_to=user,
            is_trust=False,
        ).distinct().count()
        fame = trust_count + mistrust_count
        if fame != profile.fame or \
           trust_count != profile.trust_count or \
           mistrust_count != profile.mistrust_count:
            Profile.objects.filter(pk=profile.pk).update(
                trust_count=trust_count,
                mistrust_count=mistrust_count,
                fame=fame,
            )
            n += 1
    print("%s profiles' counters re-counted. All profiles: %s" % (n, n_all,))

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201110_1300'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
