# Generated by Django 2.2.4 on 2021-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_data_recount_profile_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Логин у провайдера'),
        ),
        migrations.AlterField(
            model_name='oauth',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('telegram', 'Telegram')], max_length=100, verbose_name='Провайдер'),
        ),
    ]
