# Generated by Django 2.2.4 on 2021-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210316_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('telegram', 'Telegram'), ('yandex', 'Яндекс'), ('vk', 'ВКонтакте'), ('odnoklassniki', 'Одноклассники')], max_length=100, verbose_name='Провайдер'),
        ),
    ]
