# Generated by Django 2.2.4 on 2021-05-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0015_auto_20210331_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempToken',
            fields=[
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('type', models.PositiveIntegerField(db_index=True, editable=False)),
                ('obj_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ttl', models.PositiveIntegerField(editable=False)),
                ('ct', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
