# Generated by Django 3.1.12 on 2021-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_temptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_notified',
            field=models.BooleanField(default=True, verbose_name='Принимает уведомления'),
        ),
    ]
