# Generated by Django 3.2.6 on 2021-09-16 10:25

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Заполнить Profile.ability первой возможностью пользователя
    """
    User = apps.get_model('auth', 'User')
    for user in User.objects.filter(is_superuser=False, is_active=True).select_related('profile'):
        try:
            user.profile.ability = user.ability_set.all().order_by('insert_timestamp')[0]
            user.profile.save(update_fields=('ability',))
        except IndexError:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210915_1517'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
