# Generated by Django 3.2.6 on 2021-09-23 14:00

from django.db import migrations, connection


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    sql = 'CREATE INDEX IF NOT EXISTS auth_date_joined_idx ON auth_user (date_joined)'
    print('\nCreate auth_user date_joined index')
    with connection.cursor() as cursor:
        cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_ability'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
