# Generated by Django 3.2.6 on 2021-10-05 13:22

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_user_index_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=app.models.UnclearDateModelField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob_no_day',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob_no_month',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dod',
            field=app.models.UnclearDateModelField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dod_no_day',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dod_no_month',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
