# Generated by Django 3.2.6 on 2022-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='did_bot_start',
            field=models.BooleanField(default=False, verbose_name='Стартовал телеграм бот'),
        ),
    ]
