# Generated by Django 3.2.6 on 2022-04-21 17:28

import re

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Сделать ИОФ для пользователей, поместить их в User.first_name
    """
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all().select_related('user'):
        user = profile.user
        last_name = user.last_name
        first_name = user.first_name
        middle_name = profile.middle_name
        if middle_name and not first_name:
            iof = last_name.strip()
        else:
            iof = " ".join((first_name, middle_name, last_name,)).strip()
        iof = re.sub(r'\s{2,}', ' ', iof) or 'Без имени'
        if profile.middle_name:
            Profile.objects.filter(pk=profile.pk).update(middle_name='')
        user.last_name = ''
        user.first_name = iof
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_did_bot_start'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
