# Generated by Django 3.2.6 on 2022-04-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_data_make_iof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__first_name',)},
        ),
    ]
