# Generated by Django 3.2.6 on 2022-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_tggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth',
            name='groups',
            field=models.ManyToManyField(to='users.TgGroup', verbose_name='Группы telegram пользователя'),
        ),
    ]
