# Generated by Django 3.2.6 on 2022-09-05 13:52

import pytils
from geopy.extra.rate_limiter import RateLimiter
from geopy.geocoders import Nominatim

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass


def operation(apps, schema_editor):
    """
    Заполнить адреса пользователей, у кого не заполнены
    """
    print('\nConvert coordinates to address\n')
    Profile = apps.get_model('users', 'Profile')
    n_all = n_converted = 0
    geolocator = Nominatim(user_agent='blagodarie.org.geocoder')
    reverse = RateLimiter(geolocator.reverse, min_delay_seconds=1)
    for profile in Profile.objects.select_related('user').filter(latitude__isnull=False, longitude__isnull=False,):
        n_all += 1
        print(pytils.translit.slugify(profile.user.first_name))
        if not profile.address:
            raw = reverse('%s,%s' % (profile.latitude, profile.longitude,))
            if raw:
                address = raw.address
                if address:
                    profile.address = address
                    profile.save(update_fields=('address',))
                    n_converted += 1
                    print('    converted')
        else:
            print('    ALREADY has converted address')
    print('\n%s profiles with coordinates found, %s converted\n' % (n_all, n_converted,))

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_profile_address'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
