# Generated by Django 3.2.6 on 2022-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_data_fill_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='Умер ли?'),
        ),
    ]
