# Generated by Django 3.2.6 on 2023-01-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_is_dead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_url',
        ),
    ]
