# Generated by Django 3.2.6 on 2023-03-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_profile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('poll_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Poll Id')),
                ('question', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('message_id', models.BigIntegerField(verbose_name='Message Id')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat Id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TgPollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('answer', models.CharField(blank=True, default='', max_length=255, verbose_name='Ответ')),
                ('tgpoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tgpoll')),
            ],
            options={
                'ordering': ('tgpoll', 'number'),
                'unique_together': {('tgpoll', 'number')},
            },
        ),
        migrations.AddField(
            model_name='oauth',
            name='tg_poll_answers',
            field=models.ManyToManyField(to='users.TgPollAnswer', verbose_name='Ответы на опросы телеграм'),
        ),
    ]
