# Generated by Django 3.2.6 on 2023-03-16 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0034_auto_20230309_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('question', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('answer', models.CharField(blank=True, default='', max_length=255, verbose_name='Ответ')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.offer')),
            ],
            options={
                'ordering': ('offer', 'number'),
                'unique_together': {('offer', 'number')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_answers',
            field=models.ManyToManyField(to='users.OfferAnswer', verbose_name='Ответы на опросы/предложения'),
        ),
    ]
