# Generated by Django 3.2.6 on 2023-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230316_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='closed_timestamp',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Приостановлен'),
        ),
    ]
