# Generated by Django 3.2.6 on 2023-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_offer_closed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_multi',
            field=models.BooleanField(default=False, verbose_name='Множественный выбор'),
        ),
    ]
