# Generated by Django 4.2.1 on 2023-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_offer_is_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='question',
            field=models.CharField(max_length=2048, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='tgpoll',
            name='question',
            field=models.CharField(max_length=2048, verbose_name='Вопрос'),
        ),
    ]
