# Generated by Django 4.2.1 on 2023-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_offer_question_alter_tgpoll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tggroup',
            name='pin_message_id',
            field=models.BigIntegerField(null=True, verbose_name='Id of Message for Pin'),
        ),
    ]
