# Generated by Django 4.2.4 on 2023-12-18 13:41

import re, string, random

from django.db import migrations, IntegrityError


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Сделать короткие ссылки на пользователей

    Короткая ссылка: 10 символов, латинские строчные и прописные буквы,
    цифры, знак подчеркивания. Короткая ссылка будет в User.username
    Делаем только у тех, у кого на данный момент:
        User.username типа: '2020-04-10-19-23-30-q8dvd'
    """
    print('\nMake usernames as short IDs\n')
    chars = string.ascii_lowercase + string.digits + string.ascii_uppercase
    len_username = 10

    User = apps.get_model('auth', 'User')
    n = 0
    for user in User.objects.filter(is_superuser=False):
        if re.search(r'^\d{4}\-\d{2}\-\d{2}\-\d{2}\-\d{2}\-\d{2}\-[a-z0-9]+$', user.username):
            random.seed()
            done = False
            for i in range(1000):
                try:
                    user.username = ''.join(random.choice(chars) for x in range(len_username))
                    user.save()
                    done = True
                    break
                except IntegrityError:
                    continue
            if not done:
                print('ERROR: failed to get short id for user pk = {user.pk}')
            n += 1
    print(f'{n} usernames modified\n')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_tggroup_pin_message_id'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
