# Generated by Django 4.2.4 on 2024-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_profile_is_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editable',
            field=models.BooleanField(default=False, verbose_name='Допущено редактирование'),
        ),
    ]
