# Generated by Django 4.2.4 on 2024-05-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_data_fill_profile_acq_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='did_meet',
        ),
    ]
