# Generated by Django 5.1.3 on 2024-11-12 15:02

from django.db import migrations
from django.db.models import F


def reverse_it(apps, schema_editor):
    pass


def operation(apps, schema_editor):

    # Заполнить Profile.meet_count, число приглашенных в игру

    CurrentState = apps.get_model('contact', 'CurrentState')
    Profile = apps.get_model('users', 'Profile')
    for cs in CurrentState.objects.filter(is_invite_meet=True, is_invite_meet_reverse=False):
        Profile.objects.filter(user=cs.user_from).update(invite_meet_count=F('invite_meet_count') + 1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_profile_invite_meet_count'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
