# Generated by Django 5.1.3 on 2025-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_remove_profile_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('message_id', models.BigIntegerField(verbose_name='Message Id')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat Id')),
                ('media_group_id', models.CharField(blank=True, default='', max_length=255, verbose_name='media_group_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='tgdesc',
            field=models.ManyToManyField(to='users.tgdesc', verbose_name='Сообщения с описаниями'),
        ),
    ]
