# Generated by Django 5.1.3 on 2025-02-06 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_tgdesc_profile_tgdesc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='r_sympa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_r_sympa_set', to=settings.AUTH_USER_MODEL, verbose_name='Взаимная симпатия к'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='did_meet',
            field=models.BigIntegerField(null=True, verbose_name='Принял участие в игре знакомств'),
        ),
    ]
