# Generated by Django 5.1.3 on 2025-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_profile_r_sympa_alter_profile_did_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meet_id',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='Ид приглашения в игру знакомств'),
        ),
    ]
