# Generated by Django 5.1.3 on 2025-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_profile_meet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgdesc',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tgdesc',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='file_id'),
        ),
    ]
