# Generated by Django 5.1.3 on 2025-06-24 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_tgdesc_file_type_tgdesc_uuid_pack_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='OfferRefJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.offer')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerrefjournal_user_from_set', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerrefjournal_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный (стал referrer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferRefState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('update_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.offer')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerrefstate_user_from_set', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerrefstate_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный (стал referrer')),
            ],
            options={
                'unique_together': {('offer', 'user_from', 'user_to')},
            },
        ),
    ]
