# Generated by Django 5.1.3 on 2025-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_offer_desc_offerrefjournal_offerrefstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='desc',
        ),
        migrations.AddField(
            model_name='offer',
            name='tgdesc',
            field=models.ManyToManyField(to='users.tgdesc', verbose_name='Сообщения с описаниями'),
        ),
    ]
