# Generated by Django 4.2.1 on 2023-05-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wote', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='owner',
            new_name='creator',
        ),
    ]
