# Generated by Django 4.2.4 on 2024-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wote', '0003_rename_owner_video_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(choices=[('yt', 'Google'), ('rt', 'RuTube'), ('vk', 'ВКонтакте'), ('bn', 'Bastyon'), ('pt', 'PeerTube')], max_length=2, verbose_name='Источник'),
        ),
    ]
