# Generated by Django 2.2.4 on 2019-11-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Код ключа')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(default=0, verbose_name='Когда добавлено')),
                ('cancel_timestamp', models.BigIntegerField(null=True, verbose_name='Когда был отменен лайк')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(default=0, verbose_name='Когда добавлено')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.KeyType')),
            ],
            options={
                'unique_together': {('type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(default=0, verbose_name='Когда добавлено')),
                ('is_actual', models.BooleanField(db_index=True, default=True, verbose_name='Действующий или нет')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Key', verbose_name='Ключ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='LikeKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(default=0, verbose_name='Когда добавлено')),
                ('is_actual', models.BooleanField(db_index=True, default=True, verbose_name='Действующий или нет')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Key', verbose_name='Ключ')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Like', verbose_name='Лайк')),
            ],
            options={
                'unique_together': {('like', 'key')},
            },
        ),
    ]
