# Generated by Django 2.2.4 on 2019-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
    ]
