# Generated by Django 2.2.4 on 2019-11-27 10:48

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Заполнить количество лайков у ключа
    """
    print('Fill likes key count for every like')

    count = 0
    LikeKey = apps.get_model('contact', 'LikeKey')
    for likekey in LikeKey.objects.filter(is_actual=True, like__cancel_timestamp__isnull=True).distinct():
        likekey.key.likes_count = likekey.key.likes_count + 1
        likekey.key.save(update_fields=('likes_count',))
        count += 1
    print("%s likes pushed in keys' likes_count field" % count)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_key_likes_count'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
