# Generated by Django 2.2.4 on 2019-11-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_data_fill_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='likes_count',
        ),
    ]
