# Generated by Django 2.2.4 on 2019-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_key_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='update_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='Когда изменено'),
        ),
    ]
