# Generated by Django 2.2.4 on 2019-12-02 15:10

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Заполнить количество лайков у ключа
    """
    print('\nFill update_timestamp for every like')

    count = 0
    Like = apps.get_model('contact', 'Like')
    for like in Like.objects.all():
        if like.cancel_timestamp:
            t = like.cancel_timestamp
        else:
            t = like.insert_timestamp
        Like.objects.filter(pk=like.pk).update(update_timestamp=t)
        count += 1
    print('%s likes: update_timestamp inserted' % count)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_like_update_timestamp'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
