# Generated by Django 2.2.4 on 2019-12-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_data_fill_like_update_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='delete_timestamp',
            field=models.BigIntegerField(null=True, verbose_name='Когда удалено'),
        ),
    ]
