# Generated by Django 2.2.4 on 2019-12-02 18:53

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):

    print('\nFill UserKey delete_timestamp for every userkey')

    count = 0
    UserKey = apps.get_model('contact', 'UserKey')
    for userkey in UserKey.objects.filter(is_actual=False):
        UserKey.objects.filter(pk=userkey.pk).update(delete_timestamp=userkey.insert_timestamp + 60)
        count += 1
    print('%s userkey: delete_timestamp filled' % count)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_userkey_delete_timestamp'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
