# Generated by Django 2.2.4 on 2019-12-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_data_fill_userlike_delete_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkey',
            name='is_actual',
        ),
    ]
