# Generated by Django 2.2.4 on 2020-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_loglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='likekey',
            name='is_vague',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Не определен (vague)'),
        ),
    ]
