# Generated by Django 2.2.4 on 2020-02-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_likekey_is_vague'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likekey',
            name='is_actual',
        ),
        migrations.RemoveField(
            model_name='userkey',
            name='delete_timestamp',
        ),
    ]
