# Generated by Django 2.2.4 on 2020-02-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20200210_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likekey',
            name='is_vague',
        ),
    ]
