# Generated by Django 2.2.4 on 2020-04-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_data_fork_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='insert_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено'),
        ),
        migrations.AlterField(
            model_name='like',
            name='insert_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено'),
        ),
        migrations.AlterField(
            model_name='likekey',
            name='insert_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено'),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='insert_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено'),
        ),
        migrations.AlterField(
            model_name='usersymptom',
            name='insert_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено'),
        ),
    ]
