# Generated by Django 2.2.4 on 2020-04-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_data_fork_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptom',
            name='moon_day',
            field=models.IntegerField(default=0, verbose_name='День лунного календаря'),
        ),
    ]
