# Generated by Django 2.2.4 on 2020-04-29 18:20

from django.db import migrations

from app.utils import get_moon_day

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    print('')
    n = 0
    UserSymptom = apps.get_model('contact', 'UserSymptom')
    for usersymptom in UserSymptom.objects.all():
        usersymptom.moon_day = get_moon_day(usersymptom.insert_timestamp)
        usersymptom.save(update_fields=('moon_day',))
        n += 1
    print('%s user symptoms updated' % n)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_data_fill_moon_day'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
