# Generated by Django 2.2.4 on 2020-04-30 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_data_fill_30_moon_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptom',
            name='incognito_id',
            field=models.CharField(max_length=36, null=True, verbose_name='Идентификатор инкогнито'),
        ),
        migrations.AddField(
            model_name='usersymptom',
            name='timezone',
            field=models.IntegerField(default=300, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='usersymptom',
            name='moon_day',
            field=models.IntegerField(db_index=True, null=True, verbose_name='День лунного календаря'),
        ),
        migrations.AlterField(
            model_name='usersymptom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
