# Generated by Django 2.2.4 on 2020-05-08 11:26

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    Symptom = apps.get_model('contact', 'Symptom')
    Symptom.objects.all().update(order=None)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0024_auto_20200508_1122'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
