# Generated by Django 2.2.4 on 2020-05-08 11:32

from django.db import migrations, models

from contact.models import SymptomChecksumManage

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    SymptomChecksumManage.compute_checksum()

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_fill_symptom_order_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Порядок следования'),
        ),
        migrations.AlterUniqueTogether(
            name='symptom',
            unique_together={('group', 'order')},
        ),

        migrations.RunPython(operation, reverse_it),
    ]
