# Generated by Django 2.2.4 on 2020-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_auto_20200508_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='deprecated',
            field=models.BooleanField(default=False, verbose_name='Устарел'),
        ),
    ]
