# Generated by Django 2.2.4 on 2020-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0027_symptom_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomgroup',
            name='deprecated',
            field=models.BooleanField(default=False, verbose_name='Устарела'),
        ),
    ]
