# Generated by Django 2.2.4 on 2020-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_symptomgroup_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersymptom',
            name='incognito_id',
            field=models.CharField(db_index=True, max_length=36, null=True, verbose_name='Идентификатор инкогнито'),
        ),
    ]
