# Generated by Django 2.2.4 on 2020-05-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_auto_20200511_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersymptom',
            name='user',
        ),
    ]
