# Generated by Django 2.2.4 on 2020-05-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_data_fill_incognito_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersymptom',
            name='incognito_id',
        ),
        migrations.AlterField(
            model_name='usersymptom',
            name='incognitouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.IncognitoUser', verbose_name='Пользователь инкогнито'),
        ),
        migrations.AlterField(
            model_name='usersymptom',
            name='moon_day',
            field=models.IntegerField(db_index=True, verbose_name='День лунного календаря'),
        ),
    ]
