# Generated by Django 2.2.4 on 2020-06-30 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0033_auto_20200527_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип операции')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('operationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.OperationType', verbose_name='Тип операции')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_user_from_set', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('update_timestamp', models.BigIntegerField(default=0, verbose_name='Когда изменено')),
                ('thanks_count', models.PositiveIntegerField(default=0, verbose_name='Число благодарностей')),
                ('is_trust', models.BooleanField(default=True, verbose_name='Доверие')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentstate_user_from_set', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentstate_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
