# Generated by Django 2.2.4 on 2020-06-30 18:57

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Удалить ключ GoogleAccountId и всё, что на него завязано
    """
    KeyType = apps.get_model('contact', 'KeyType')
    try:
        key = KeyType.objects.get(title='GoogleAccountId')
        key.delete()
    except KeyType.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_currentstate_journal_operationtype'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
