# Generated by Django 2.2.4 on 2020-08-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0035_data_remove_google_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('update_timestamp', models.BigIntegerField(default=0, verbose_name='Когда изменено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
