# Generated by Django 2.2.4 on 2020-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
    ]
