# Generated by Django 2.2.4 on 2020-08-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0037_journal_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('text', models.CharField(db_index=True, max_length=2048, unique=True, verbose_name='Значение')),
                ('fame', models.PositiveIntegerField(default=0, verbose_name='Известность')),
                ('sum_thanks_count', models.PositiveIntegerField(default=0, verbose_name='Число благодарностей')),
                ('trustless_count', models.PositiveIntegerField(default=0, verbose_name='Число утрат доверия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentstate_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='anytext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.AnyText', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='journal',
            name='anytext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.AnyText', verbose_name='Текст'),
        ),
        migrations.AlterUniqueTogether(
            name='currentstate',
            unique_together={('user_from', 'anytext'), ('user_from', 'user_to')},
        ),
    ]
