# Generated by Django 2.2.4 on 2020-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0038_auto_20200818_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_reverse',
            field=models.BooleanField(default=False, verbose_name='Обратное отношение'),
        ),
    ]
