# Generated by Django 2.2.4 on 2020-09-22 14:48

from django.db import migrations

def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    print('')
    n = n_all = 0
    CurrentState = apps.get_model('contact', 'CurrentState')
    for cs in CurrentState.objects.filter(user_to__isnull=False, is_reverse=False).distinct():
        cs_reverse, created_ = CurrentState.objects.get_or_create(
            user_to=cs.user_from,
            user_from=cs.user_to,
            defaults=dict(
                is_reverse=True,
                thanks_count=cs.thanks_count,
                is_trust=cs.is_trust
        ))
        if created_:
            n += 1
        n_all += 1
    print("%s cussentState's fake reverse records inserted. All records: %s" % (n, n_all,))

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0039_currentstate_is_reverse'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
