# Generated by Django 2.2.4 on 2020-09-24 11:00

from django.db import migrations, connection

def reverse_it(apps, schema_editor):
    pass

# TODO Drop this table

def operation(apps, schema_editor):
    ops = """
        create temp table if not exists tmp1(
            level int,
            user_from_id int,
            user_to_id int,
            thanks_count int,
            is_trust boolean,
            is_reverse boolean
        ) ON COMMIT delete rows;

        create index if not exists idx_tmp1_1 on tmp1(level);

        create index if not exists idx_tmp1_2 on tmp1(user_from_id);

        create index if not exists idx_tmp1_3 on tmp1(user_to_id);

        create unlogged table if not exists template_tmp1 (like tmp1);
    """
    print('')
    for op in ops.split("\n\n"):
        sql = op.strip()
        print('Preform Postgresql command:\n', sql)
        with connection.cursor() as cursor:
            result = cursor.execute(sql)
            print(result)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0040_data_fill_connection_is_reserve'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
