# Generated by Django 2.2.4 on 2020-10-09 13:39

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    print('')
    n = n_all = 0
    CurrentState = apps.get_model('contact', 'CurrentState')
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all().select_related('user'):
        n_all += 1
        old_fame = profile.fame
        new_fame = CurrentState.objects.filter(
            is_reverse=False,
            user_to=profile.user,
        ).distinct().count()
        if old_fame != new_fame:
            profile.fame = new_fame
            profile.save()
            n += 1
    print("%s profiles' fame(s) re-counted. All profiles: %s" % (n, n_all,))


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0043_data_func_find_rel'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
