# Generated by Django 2.2.4 on 2020-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0045_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='update_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено'),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='update_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено'),
        ),
        migrations.AlterField(
            model_name='like',
            name='update_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='update_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Когда изменено'),
        ),
    ]
