# Generated by Django 2.2.4 on 2020-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0046_auto_20201023_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anytext',
            old_name='trustless_count',
            new_name='mistrust_count',
        ),
        migrations.AddField(
            model_name='anytext',
            name='trust_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число оказанных доверий'),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='is_trust',
            field=models.NullBooleanField(default=None, verbose_name='Доверие'),
        ),
    ]
