# Generated by Django 3.2.6 on 2021-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0049_data_func_find_rel_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Текст'),
        ),
    ]
