# Generated by Django 3.2.6 on 2021-09-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0050_auto_20210906_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogLike',
        ),
    ]
