# Generated by Django 3.2.6 on 2021-09-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0051_delete_loglike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likekey',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likekey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='likekey',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='LikeKey',
        ),
    ]
