# Generated by Django 3.2.6 on 2021-09-22 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0052_auto_20210922_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
