# Generated by Django 3.2.6 on 2021-09-22 14:58

from django.db import migrations, connection


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    with connection.cursor() as cursor:
        print('\nRemove find_rel function if exists')
        cursor.execute(
            'drop function if exists find_rel(v_user_from_id int, v_level int, do_reverse boolean)'
        )
        print('Remove contact_key records with former null and now pointing to owner_id=1')
        cursor.execute(
            'delete from contact_key where owner_id=1'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0053_auto_20210922_1415'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
