# Generated by Django 3.2.6 on 2021-10-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0054_data_after_remove_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Родитель'),
        ),
    ]
