# Generated by Django 3.2.6 on 2021-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0056_data_func_find_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_child',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Потомок'),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='is_parent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Родитель'),
        ),
    ]
