# Generated by Django 3.2.6 on 2021-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0058_data_for_is_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTmpParent',
            fields=[
###                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('user_from_id', models.IntegerField(blank=True, null=True)),
                ('user_to_id', models.IntegerField(blank=True, null=True)),
                ('thanks_count', models.IntegerField(blank=True, null=True)),
                ('is_trust', models.BooleanField(blank=True, null=True)),
                ('is_parent', models.BooleanField(blank=True, null=True)),
                ('is_child', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template_tmp_parent',
                'managed': False,
            },
        ),
    ]
