# Generated by Django 3.2.6 on 2021-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0060_data_func_find_parent_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_father',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отец'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='is_mother',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Мать'),
        ),
    ]
