# Generated by Django 3.2.6 on 2021-10-25 13:06

from django.db import migrations
from django.db.models.query_utils import Q

def reverse_it(apps, schema_editor):
    pass


def operation(apps, schema_editor):
    print('')
    print ('Fill CurrentState is_father, is_mother')
    GENDER_DEFAULT = 'm'
    n_all = n_default = n_filled = 0
    CurrentState = apps.get_model('contact', 'CurrentState')
    q = Q(is_parent=True) | Q(is_child=True)
    for cs in CurrentState.objects.filter(q).distinct():
        n_all += 1
        if cs.is_parent:
            parent_gender = cs.user_to.profile.gender
            if parent_gender:
                n_filled += 1
                if parent_gender == 'm':
                    cs.is_father = True
                elif parent_gender == 'f':
                    cs.is_mother = True
                else:
                    raise Exception('Invalid gender in profile id: %s' % cs.user_to.profile.pk)
            else:
                n_default += 1
                if GENDER_DEFAULT == 'm':
                    cs.is_father = True
                else:
                    cs.is_mother = True
        elif cs.is_child:
            parent_gender = cs.user_from.profile.gender
            if parent_gender:
                n_filled += 1
                if parent_gender == 'm':
                    cs.is_father = True
                elif parent_gender == 'f':
                    cs.is_mother = True
                else:
                    raise Exception('Invalid gender in profile id: %s' % cs.user_to.profile.pk)
            else:
                n_default += 1
                if GENDER_DEFAULT == 'm':
                    cs.is_father = True
                else:
                    cs.is_mother = True
        cs.save()

    print(
        'OK. %(n_all)s parent recs all, '
        '%(n_filled)s filled correct, '
        '%(n_default)s filled by default' % dict(
            n_all = n_all, n_filled=n_filled, n_default=n_default,
    ))

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0061_auto_20211025_1306'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
