# Generated by Django 3.2.6 on 2021-10-25 13:17

from django.db import migrations, connection


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    ops = """
        drop function if exists find_rel_parent_child;

        drop table if exists template_tmp_parent;

        create temp table tmp_parent(
            level int,
            user_from_id int,
            user_to_id int,
            thanks_count int,
            is_trust boolean,
            is_father boolean,
            is_mother boolean,
            is_child boolean
        ) ON COMMIT delete rows;

        create unlogged table if not exists template_tmp_parent (like tmp_parent);
    """
    print('recreate template_tmp_parent table')
    for op in ops.split("\n\n"):
        sql = op.strip()
        print('Preform Postgresql command:\n', sql)
        with connection.cursor() as cursor:
            result = cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0062_data_fill_mother_father'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
