# Generated by Django 3.2.6 on 2021-10-27 14:26

from django.db import migrations, connection


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    ops = """
        drop function if exists find_rel;

        drop function if exists find_rel_parent;

        drop table if exists template_tmp1;

    """
    print('\nRemove unused "find_rel", "find_rel_parent" functions, "template_tmp1" table')
    for op in ops.strip().split("\n\n"):
        sql = op.strip()
        print('Preform Postgresql command:\n', sql)
        with connection.cursor() as cursor:
            result = cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0065_remove_currentstate_is_parent'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
