# Generated by Django 3.2.6 on 2021-10-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0066_data_remove_unused'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateTmp1',
        ),
    ]
