# Generated by Django 3.2.6 on 2021-12-07 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0067_delete_templatetmp1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTmpLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('user_from_id', models.IntegerField(blank=True, null=True)),
                ('user_to_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template_tmp_links',
                'managed': False,
            },
        ),
    ]
