# Generated by Django 3.2.6 on 2022-02-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0071_data_func_find_mother_father_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chat_id', models.BigIntegerField(verbose_name='Chat Id')),
                ('message_id', models.BigIntegerField(verbose_name='Message Id')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.journal', verbose_name='Журнал')),
            ],
        ),
    ]
