# Generated by Django 3.2.6 on 2022-05-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0072_tgjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessageJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Когда добавлено')),
                ('from_chat_id', models.BigIntegerField(verbose_name='Chat Id')),
                ('message_id', models.BigIntegerField(verbose_name='Message Id')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_message_journal_user_from_set', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_message_journal_user_to_set', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
                ('user_to_delivered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_message_journal_user_to_delivered_set', to=settings.AUTH_USER_MODEL, verbose_name='Кому доставлено')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
