# Generated by Django 3.2.6 on 2022-09-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0075_func_find_trust_relation_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateTmpLinks',
        ),
        migrations.DeleteModel(
            name='TemplateTmpParent',
        ),
    ]
