# Generated by Django 3.2.6 on 2022-12-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0079_data_func_chat_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessagejournal',
            name='operationtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.operationtype', verbose_name='Тип операции'),
        ),
    ]
