# Generated by Django 4.2.4 on 2024-03-28 14:10

from django.db import migrations
from django.db.models import Sum


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):
    """
    Подправить CurrentState.thanks_count & Profile.sum_thanks_count
    """
    CurrentState = apps.get_model('contact', 'CurrentState')
    Profile = apps.get_model('users', 'Profile')

    n = 0
    for cs in CurrentState.objects.filter(thanks_count__gt=0):
        cs.thanks_count -= 1
        if cs.thanks_count <= 0:
            cs.thanks_count = 0
        cs.save(update_fields=('thanks_count',))
        n += 1
    print(f'\n{n} CurrentState records modified\n')

    n = 0
    for profile in Profile.objects.select_related('user').filter(sum_thanks_count__gt=0):
        profile.sum_thanks_count = CurrentState.objects.filter(
            user_to=profile.user,
        ).distinct().aggregate(Sum('thanks_count'))['thanks_count__sum'] or 0
        profile.save(update_fields=('sum_thanks_count',))
        n += 1
    print(f'{n} Profile records modified\n')


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0081_data_func_genesis'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
