# Generated by Django 4.2.4 on 2024-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0082_data_thanks_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='attitude',
            field=models.CharField(choices=[('a', 'Знаком(а)'), ('t', 'Доверяет'), ('mt', 'Не доверяет')], db_index=True, max_length=2, null=True, verbose_name='Отношение'),
        ),
    ]
