# Generated by Django 4.2.4 on 2024-04-05 14:14

from django.db import migrations, connection

# Функции postgres рекрсивного поиска по довериям, знакомствам
#
# Attribution:
# https://www.alibabacloud.com/blog/applying-postgresql-graph-database-to-social-scenarios_595035


def reverse_it(apps, schema_editor):
    pass


def operation(apps, schema_editor):
    ops = """
drop function find_trust_tree(int, int)
\f
create function find_trust_tree(
    v_user_from_id int,
    v_level int
) returns setof template_tmp_links as 
$$

-- Дерево доверий/знакомств, начиная с пользователя v_user_from_id
--  v_level:
--      максимальное число итераций при проходе по дереву связей
--

declare 
    i int := 1;
begin 
    if v_level <= 0 then 
        raise notice 'level must >= 1'; 
        return; 
    end if; 
  
    create temp table tmp(like template_tmp_links) ON COMMIT delete rows;
    create index if not exists idx_tmp_trust_1 on tmp(level);
    create index if not exists idx_tmp_trust_2 on tmp(user_from_id);
    create index if not exists idx_tmp_trust_3 on tmp(user_to_id);

    return query
        insert into tmp
            select
                i,
                user_from_id,
                user_to_id
            from
                contact_currentstate
            where
                (user_from_id=v_user_from_id) and
                (user_to_id is not null)      and
                (attitude in ('t', 'a'))
    returning *;

    loop
        i := i + 1; 

        -- All levels of data has been found
        if i > v_level then
            return;
        end if; 

        -- The next level relation is derived though a join with level=i-1
        -- (Group By excludes duplicate nodes.
        -- For example, 3 in 1-2-3-4 and 1-5-3-4 is excluded),
        -- and the looping points are excluded by not exists.
        --
        return query 
            insert into tmp
                select
                    i,
                    contact_currentstate.user_from_id,
                    contact_currentstate.user_to_id
                from
                    contact_currentstate
                join
                    (select user_to_id from tmp where level = i - 1 group by user_to_id)
                tmp on
                    (contact_currentstate.user_from_id = tmp.user_to_id)
                where
                    (contact_currentstate.user_to_id is not null)  and
                    (contact_currentstate.attitude in ('t', 'a'))  and
                    not exists (
                        select 1 from tmp where contact_currentstate.user_from_id = tmp.user_from_id
                    )
        returning *;
  end loop; 
end;

$$
    language plpgsql strict
\f
drop function find_trust_path_shortest(int, int, int)
\f
create function find_trust_path_shortest(
    v_user_from_id int,
    v_user_to_id int,
    v_level int
) returns setof template_tmp_links_paths as 
$$
declare 
    i int := 1; 
begin 
    if v_level <= 0 then 
        raise notice 'level must >= 1'; 
        return; 
    end if; 
  
    create temp table if not exists tmp(like template_tmp_links_paths) ON COMMIT delete rows;
    create index if not exists idx_tmp_links_1 on tmp(level);
    create index if not exists idx_tmp_links_2 on tmp(user_from_id);
    create index if not exists idx_tmp_links_3 on tmp(user_to_id);

    return query
        insert into tmp
            select
                i,
                array[]::int[] || user_from_id || user_to_id,
                user_from_id,
                user_to_id
            from
                contact_currentstate
            where
                (user_from_id = v_user_from_id) and
                (user_to_id is not null)        and
                (attitude in ('t', 'a'))
    returning *; 

    loop
        i := i + 1; 
        if i > v_level then
            return;
        end if; 

        if exists (
            select
                1
            from
                tmp
            where
                user_to_id = v_user_to_id and
                level = i - 1
        ) then
            return;
        end if;

        return query
            insert into tmp
                select
                    i,
                    tmp.path || contact_currentstate.user_to_id,
                    contact_currentstate.user_from_id,
                    contact_currentstate.user_to_id
                from
                    contact_currentstate
                join
                    (select user_to_id, path from tmp where level = i - 1)
                tmp on
                    (contact_currentstate.user_from_id = tmp.user_to_id)
                where
                    (contact_currentstate.user_to_id is not null)  and
                    (contact_currentstate.attitude in ('t', 'a'))  and
                    not exists (
                        select 1 from tmp where contact_currentstate.user_from_id = tmp.user_from_id
                    )
        returning *; 
    end loop; 
end;

$$
    language plpgsql strict
"""

    print('\nRecreate postgresql recursive search functions')
    for op in ops.split("\n\f\n"):
        sql = op.strip()
        with connection.cursor() as cursor:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0085_remove_currentstate_is_trust'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
