# Generated by Django 4.2.4 on 2024-10-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0086_data_trusts_recursions'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_sympa',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Симпатия'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='is_sympa_reverse',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Симпатия: обратное отношение'),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='is_reverse',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Обратное отношение'),
        ),
    ]
