# Generated by Django 4.2.4 on 2024-10-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0087_currentstate_is_sympa_currentstate_is_sympa_reverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_invite_meet',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Приглашение в игру знакомств'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='is_invite_meet_reverse',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Приглашение в игру знакомств: обратное отношение'),
        ),
    ]
