# Generated by Django 4.2.4 on 2024-10-29 12:49

from django.db import migrations


def reverse_it(apps, schema_editor):
    pass

def operation(apps, schema_editor):

    # Задачи:
    #   1.  Исправить в contact_journal, поменяв местами user_from, user_to
    #   2.  Пройтись по журналу и вставить записи в contact_currentstate
    #       кто кого пригласил в игру знакомств

    DID_MEET = INVITE_MEET = 12
    Journal = apps.get_model('contact', 'Journal')
    CurrentState = apps.get_model('contact', 'CurrentState')
    for journal in Journal.objects.filter(operationtype_id = DID_MEET, user_to__isnull=False):
        tempo = journal.user_to
        journal.user_to = journal.user_from
        journal.user_from = tempo
        journal.save()
        cs, created = CurrentState.objects.get_or_create(
            user_from=journal.user_from,
            user_to=journal.user_to,
            defaults = dict(
                is_invite_meet=True,
                is_invite_meet_reverse=False,
        ))
        if not created:
            cs.is_invite_meet = True
            cs.is_invite_meet_reverse = False
            cs.save()

        # reverse record
        cs, created = CurrentState.objects.get_or_create(
            user_from=journal.user_to,
            user_to=journal.user_from,
            defaults = dict(
                is_invite_meet=True,
                is_invite_meet_reverse=True,
        ))
        if not created and not cs.is_invite_meet:
            cs.is_invite_meet = True
            cs.is_invite_meet_reverse = True
            cs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0088_currentstate_is_invite_meet_and_more'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_it),
    ]
