# Generated by Django 5.1.3 on 2025-01-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0089_data_fill_meet_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.TextField(db_index=True, verbose_name='Значение'),
        ),
    ]
