# Generated by Django 5.1.3 on 2025-01-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0090_alter_key_value'),
        ('users', '0051_tgdesc_profile_tgdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='tgdesc',
            field=models.ManyToManyField(to='users.tgdesc', verbose_name='Описание: (составное) сообщение из телеграма'),
        ),
    ]
