# Generated by Django 5.1.3 on 2025-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0091_journal_tgdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_sympa_confirmed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Подтверждение интереса'),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='is_sympa',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Интерес'),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='is_sympa_reverse',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Интерес: обратное отношение'),
        ),
    ]
