# Generated by Django 5.1.3 on 2025-02-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0092_currentstate_is_sympa_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='is_hide_meet',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыт в игре знакомств'),
        ),
    ]
