# Generated by Django 5.1.3 on 2025-04-08 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0093_currentstate_is_hide_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessagejournal',
            name='caption',
            field=models.TextField(default='', verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tgmessagejournal',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='file_id'),
        ),
        migrations.AddField(
            model_name='tgmessagejournal',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Тип медиа'),
        ),
        migrations.AddField(
            model_name='tgmessagejournal',
            name='media_group_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='media_group_id'),
        ),
        migrations.AddField(
            model_name='tgmessagejournal',
            name='uuid_pack',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
