# Generated by Django 5.1.3 on 2025-06-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0095_data_fill_uuid_pack'),
        ('users', '0057_remove_offer_desc_offer_tgdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='offer_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.offeranswer', verbose_name='Ответ на опрос/предложение'),
        ),
    ]
